const products = [
  {
    id: "3",
    name: "Adidas Originals 3-Stripe Denim Maxi Skirt",
    category: "Women",
    subcategory: "New In",
    price: 79.99,
    stock: 15,
    badge: "Bestseller",
    image_url: "https://applause.co.zw/uploads/3.jpg",
    description: "The perfect blend of classic athletic heritage and contemporary streetwear. Elevate your casual rotation with this standout Adidas Originals denim maxi skirt.",
    created_at: new Date("2025-01-15")
  },
  {
    id: "4",
    name: "Adidas Originals 2-Piece Denim Set",
    category: "Women",
    subcategory: "Clothing",
    price: 110.00,
    stock: 12,
    badge: "New In",
    image_url: "https://applause.co.zw/uploads/4.jpg",
    description: "Make a bold, retro-sporty statement with this effortlessly coordinated 2-piece denim set featuring a cropped jacket and flared skirt.",
    created_at: new Date("2025-02-01")
  },
  {
    id: "5",
    name: "Adidas Originals 2-Piece Acid-Wash Denim Set",
    category: "Women",
    subcategory: "Discover",
    price: 110.00,
    stock: 10,
    badge: "New In",
    image_url: "https://applause.co.zw/uploads/unnamed_1.jpg",
    description: "Bold acid-wash denim jacket and skirt set from Adidas Originals. A head-turning retro-sporty look.",
    created_at: new Date("2025-02-05")
  },
  {
    id: "6",
    name: "Alo Yoga Crystal Rhinestone 2-Piece Tracksuit",
    category: "Women",
    subcategory: "Womens Sport",
    price: 185.00,
    stock: 8,
    badge: "Bestseller",
    image_url: "https://applause.co.zw/uploads/unnamed_2.jpg",
    description: "Luxury meets athleisure in this crystal rhinestone logo tracksuit set with zip jacket and wide-leg pants.",
    created_at: new Date("2025-01-20")
  },
  {
    id: "8",
    name: "Ferrari Michael Schumacher Racing Jacket",
    category: "Men",
    subcategory: "Mens Sport",
    price: 229.99,
    stock: 5,
    badge: "Bestseller",
    image_url: "https://applause.co.zw/uploads/unnamed_4.jpg",
    description: "Red leather racing jacket honouring Michael Schumacher's legendary career. A collector's piece for motorsport fans.",
    created_at: new Date("2025-01-10")
  },
  {
    id: "9",
    name: "Adidas Originals Leopard Print Firebird Tracksuit",
    category: "Women",
    subcategory: "Womens Sport",
    price: 150.00,
    stock: 10,
    badge: "New In",
    image_url: "https://applause.co.zw/uploads/unnamed_5.jpg",
    description: "Stand out in this leopard print Firebird tracksuit set with zip jacket and wide-leg pants.",
    created_at: new Date("2025-02-10")
  },
  {
    id: "10",
    name: "Adidas Originals 3-Stripe Wide-Leg Jumpsuit",
    category: "Women",
    subcategory: "Clothing",
    price: 125.00,
    stock: 12,
    badge: "New In",
    image_url: "https://applause.co.zw/uploads/unnamed_6.jpg",
    description: "Short-sleeve wide-leg jumpsuit with iconic 3-Stripe detailing. Effortless one-piece styling.",
    created_at: new Date("2025-02-08")
  },
  {
    id: "11",
    name: "Adidas Originals High-Neck Cropped Tracksuit",
    category: "Women",
    subcategory: "Womens Sport",
    price: 140.00,
    stock: 10,
    badge: "Bestseller",
    image_url: "https://applause.co.zw/uploads/unnamed_7.jpg",
    description: "High-neck cropped tracksuit set with jacket and wide-leg pants. Modern athletic elegance.",
    created_at: new Date("2025-01-25")
  },
  {
    id: "13",
    name: "Adidas Originals Leopard Print Resort Set",
    category: "Women",
    subcategory: "Clothing",
    price: 95.00,
    stock: 14,
    badge: "Bestseller",
    image_url: "https://applause.co.zw/uploads/unnamed_9.jpg",
    description: "Leopard print resort collar button-up shirt and shorts set. Vacation-ready style.",
    created_at: new Date("2025-01-30")
  },
  {
    id: "14",
    name: "Adidas Originals High-Neck Cropped Tracksuit Set",
    category: "Women",
    subcategory: "Womens Sport",
    price: 140.00,
    stock: 10,
    badge: "Bestseller",
    image_url: "https://applause.co.zw/uploads/unnamed_10.jpg",
    description: "High-neck cropped jacket paired with wide-leg pants. Premium athletic set.",
    created_at: new Date("2025-01-28")
  },
  {
    id: "15",
    name: "Adidas Originals Forest Green Track Set",
    category: "Women",
    subcategory: "Clothing",
    price: 130.00,
    stock: 10,
    badge: "New In",
    image_url: "https://applause.co.zw/uploads/unnamed_12.jpg",
    description: "Forest green track jacket and midi skirt set. Sporty sophistication in rich colour.",
    created_at: new Date("2025-02-12")
  },
  {
    id: "16",
    name: "Vintage Marlboro Racing Leather Moto Jacket",
    category: "Men",
    subcategory: "Clothing",
    price: 215.00,
    stock: 4,
    badge: "Bestseller",
    image_url: "https://applause.co.zw/uploads/unnamed_13.jpg",
    description: "Vintage Marlboro racing leather moto jacket. A rare collector's piece for motorsport enthusiasts.",
    created_at: new Date("2025-01-05")
  },
  {
    id: "17",
    name: "Adidas Originals Mesh Knit & Pleated Midi Set",
    category: "Women",
    subcategory: "Clothing",
    price: 115.00,
    stock: 10,
    badge: "New In",
    image_url: "https://applause.co.zw/uploads/unnamed_14.jpg",
    description: "Mesh knit top and pleated midi skirt set. Contemporary elegance meets sporty design.",
    created_at: new Date("2025-02-14")
  },
  {
    id: "18",
    name: "Adidas Originals Resort Shirt & Shorts Set",
    category: "Women",
    subcategory: "Clothing",
    price: 95.00,
    stock: 12,
    badge: "New In",
    image_url: "https://applause.co.zw/uploads/unnamed_15.jpg",
    description: "Resort collar button-up shirt and shorts set. Relaxed warm-weather coordinates.",
    created_at: new Date("2025-02-02")
  },
  {
    id: "19",
    name: "Louis Vuitton Monogram Inspired Denim Set",
    category: "Women",
    subcategory: "Clothing",
    price: 165.00,
    stock: 6,
    badge: "Bestseller",
    image_url: "https://applause.co.zw/uploads/unnamed_16.jpg",
    description: "Monogram-inspired 2-piece denim set with bomber jacket and tiered ruffle skirt. Luxury streetwear.",
    created_at: new Date("2025-01-22")
  },
  {
    id: "20",
    name: "Sleeveless Pleated A-Line Maxi Dress",
    category: "Women",
    subcategory: "New In",
    price: 85.00,
    stock: 15,
    badge: "New In",
    image_url: "https://applause.co.zw/uploads/unnamed_17.jpg",
    description: "Sleeveless pleated A-line maxi dress. Elegant silhouette for any occasion.",
    created_at: new Date("2025-02-06")
  },
  {
    id: "21",
    name: "Adidas Originals Spezial Red Suede Sneakers",
    category: "Men",
    subcategory: "Shoes",
    price: 110.00,
    stock: 8,
    badge: "Bestseller",
    image_url: "https://applause.co.zw/uploads/unnamed_18.jpg",
    description: "Red suede sneakers with gum sole. Iconic Adidas Originals heritage style.",
    created_at: new Date("2025-01-18")
  },
  {
    id: "22",
    name: "Vintage Red Bull Racing Leather Moto Jacket",
    category: "Women",
    subcategory: "Clothing",
    price: 225.00,
    stock: 4,
    badge: "Bestseller",
    image_url: "https://applause.co.zw/uploads/unnamed_20.jpg",
    description: "Vintage Red Bull Racing leather moto jacket. Statement piece for racing fans.",
    created_at: new Date("2025-01-12")
  },
  {
    id: "23",
    name: "Vintage Western Studded Leather Jacket",
    category: "Men",
    subcategory: "Clothing",
    price: 195.00,
    stock: 5,
    badge: null,
    image_url: "https://applause.co.zw/uploads/unnamed_21.jpg",
    description: "Western studded leather jacket with back graphic. Rock and roll attitude.",
    created_at: new Date("2025-01-08")
  },
  {
    id: "24",
    name: "Vintage Monster Energy Racing Leather Jacket",
    category: "Men",
    subcategory: "Mens Sport",
    price: 220.00,
    stock: 4,
    badge: "Bestseller",
    image_url: "https://applause.co.zw/uploads/unnamed_22.jpg",
    description: "Monster Energy racing leather moto jacket. Bold motorsport style.",
    created_at: new Date("2025-01-14")
  },
  {
    id: "25",
    name: "Vintage Sinister Gang Crest Cropped Biker Jacket",
    category: "Men",
    subcategory: "Discover",
    price: 240.00,
    stock: 3,
    badge: "New In",
    image_url: "https://applause.co.zw/uploads/unnamed_23.jpg",
    description: "Cropped leather biker jacket with crest graphic. Edgy vintage style.",
    created_at: new Date("2025-02-15")
  },
  {
    id: "26",
    name: "Vintage McLaren Racing Leather Bomber Jacket",
    category: "Men",
    subcategory: "Clothing",
    price: 230.00,
    stock: 4,
    badge: null,
    image_url: "https://applause.co.zw/uploads/unnamed_24.jpg",
    description: "McLaren Racing leather Grand Prix bomber jacket. Premium motorsport heritage.",
    created_at: new Date("2025-01-20")
  },
  {
    id: "27",
    name: "Vintage Dainese Yama Moto 72 Racing Jacket",
    category: "Men",
    subcategory: "Clothing",
    price: 235.00,
    stock: 3,
    badge: null,
    image_url: "https://applause.co.zw/uploads/unnamed_25.jpg",
    description: "Dainese Yama Moto 72 leather racing jacket. Italian craftsmanship meets racing legacy.",
    created_at: new Date("2025-01-26")
  },
  {
    id: "28",
    name: "Vintage Avirex Two-Tone Leather Varsity Jacket",
    category: "Men",
    subcategory: "Clothing",
    price: 260.00,
    stock: 3,
    badge: null,
    image_url: "https://applause.co.zw/uploads/unnamed_26.jpg",
    description: "Avirex New York two-tone leather varsity jacket. American heritage luxury.",
    created_at: new Date("2025-01-03")
  },
  {
    id: "29",
    name: "Vintage Yamaha Racing Leather Moto Jacket",
    category: "Men",
    subcategory: "Clothing",
    price: 225.00,
    stock: 4,
    badge: "Bestseller",
    image_url: "https://applause.co.zw/uploads/unnamed_28.jpg",
    description: "Yamaha Racing leather moto jacket. Iconic racing branding on premium leather.",
    created_at: new Date("2025-01-07")
  },
  {
    id: "30",
    name: "Vintage EPIUM Studded Leather Bomber Jacket",
    category: "Men",
    subcategory: "Mens Sport",
    price: 250.00,
    stock: 3,
    badge: "New In",
    image_url: "https://applause.co.zw/uploads/unnamed_29.jpg",
    description: "EPIUM studded 00 leather bomber jacket. Statement piece with rock-inspired detailing.",
    created_at: new Date("2025-02-02")
  },
  {
    id: "31",
    name: "Vintage Scarface Half-and-Half Leather Bomber",
    category: "Men",
    subcategory: "Mens Sport",
    price: 250.00,
    stock: 3,
    badge: "Bestseller",
    image_url: "https://applause.co.zw/uploads/unnamed_30.jpg",
    description: "Scarface half-and-half leather bomber jacket. Cinematic style meets luxury outerwear.",
    created_at: new Date("2025-01-16")
  },
  {
    id: "32",
    name: "Vintage Japanese Kanji Graphic Leather Jacket",
    category: "Men",
    subcategory: "Clothing",
    price: 220.00,
    stock: 4,
    badge: null,
    image_url: "https://applause.co.zw/uploads/unnamed_31.jpg",
    description: "Japanese Kanji graphic leather moto jacket. Cultural fusion meets vintage leather.",
    created_at: new Date("2025-01-22")
  },
  {
    id: "33",
    name: "Vintage NY Monogram Studded Leather Bomber",
    category: "Men",
    subcategory: "Clothing",
    price: 245.00,
    stock: 3,
    badge: "Bestseller",
    image_url: "https://applause.co.zw/uploads/unnamed_33.jpg",
    description: "NY monogram studded leather bomber jacket. Urban luxury with rock-inspired studs.",
    created_at: new Date("2025-01-09")
  },
  {
    id: "34",
    name: "Vintage Ferrari Racing Leather Moto Jacket",
    category: "Men",
    subcategory: "Mens Sport",
    price: 230.00,
    stock: 4,
    badge: "New In",
    image_url: "https://applause.co.zw/uploads/unnamed_34.jpg",
    description: "Ferrari racing leather moto jacket. Legendary Italian motorsport heritage.",
    created_at: new Date("2025-02-10")
  }
];

const adminCredentials = {
  username: "admin",
  password: "found2025"
};

const customers = [
  { id: "1", name: "Tatenda Moyo", phone: "+263771234567", email: "tatenda@email.com", orders: 3, total_spent: 185.00, since: "2025-01-10" },
  { id: "2", name: "Nkosazana Dlamini", phone: "+263772345678", email: "nkosa@email.com", orders: 1, total_spent: 78.00, since: "2025-01-20" },
  { id: "3", name: "Blessing Chikowero", phone: "+263773456789", email: "blessing@email.com", orders: 5, total_spent: 312.00, since: "2025-01-05" },
  { id: "4", name: "Rudo Mapfumo", phone: "+263774567890", email: "", orders: 2, total_spent: 96.00, since: "2025-02-01" },
  { id: "5", name: "Tawanda Sithole", phone: "+263775678901", email: "tawanda@email.com", orders: 1, total_spent: 89.00, since: "2025-02-05" }
];

module.exports = { products, adminCredentials, customers };
