const products = [
  {
    id: "3",
    name: "Adidas Originals 3-Stripe Denim Maxi Skirt",
    category: "Women",
    subcategory: "New In",
    price: 79.99,
    stock: 15,
    badge: "Bestseller",
    image_url: "https://applause.co.zw/uploads/3.jpg",
    description: "The perfect blend of classic athletic heritage and contemporary streetwear. Elevate your casual rotation with this standout Adidas Originals denim maxi skirt.",
    created_at: new Date("2025-01-15")
  },
  {
    id: "4",
    name: "Adidas Originals 2-Piece Denim Set",
    category: "Women",
    subcategory: "Clothing",
    price: 110.00,
    stock: 12,
    badge: "New In",
    image_url: "https://applause.co.zw/uploads/4.jpg",
    description: "Make a bold, retro-sporty statement with this effortlessly coordinated 2-piece denim set featuring a cropped jacket and flared skirt.",
    created_at: new Date("2025-02-01")
  },
  {
    id: "5",
    name: "Adidas Originals 2-Piece Acid-Wash Denim Set",
    category: "Women",
    subcategory: "Discover",
    price: 110.00,
    stock: 10,
    badge: "New In",
    image_url: "https://applause.co.zw/uploads/unnamed_1.jpg",
    description: "Bold acid-wash denim jacket and skirt set from Adidas Originals. A head-turning retro-sporty look.",
    created_at: new Date("2025-02-05")
  },
  {
    id: "6",
    name: "Alo Yoga Crystal Rhinestone 2-Piece Tracksuit",
    category: "Women",
    subcategory: "Womens Sport",
    price: 185.00,
    stock: 8,
    badge: "Bestseller",
    image_url: "https://applause.co.zw/uploads/unnamed_2.jpg",
    description: "Luxury meets athleisure in this crystal rhinestone logo tracksuit set with zip jacket and wide-leg pants.",
    created_at: new Date("2025-01-20")
  },
  {
    id: "8",
    name: "Ferrari Michael Schumacher Racing Jacket",
    category: "Men",
    subcategory: "Mens Sport",
    price: 229.99,
    stock: 5,
    badge: "Bestseller",
    image_url: "https://applause.co.zw/uploads/unnamed_4.jpg",
    description: "Red leather racing jacket honouring Michael Schumacher's legendary career. A collector's piece for motorsport fans.",
    created_at: new Date("2025-01-10")
  },
  {
    id: "9",
    name: "Adidas Originals Leopard Print Firebird Tracksuit",
    category: "Women",
    subcategory: "Womens Sport",
    price: 150.00,
    stock: 10,
    badge: "New In",
    image_url: "https://applause.co.zw/uploads/unnamed_5.jpg",
    description: "Stand out in this leopard print Firebird tracksuit set with zip jacket and wide-leg pants.",
    created_at: new Date("2025-02-10")
  },
  {
    id: "10",
    name: "Adidas Originals 3-Stripe Wide-Leg Jumpsuit",
    category: "Women",
    subcategory: "Clothing",
    price: 125.00,
    stock: 12,
    badge: "New In",
    image_url: "https://applause.co.zw/uploads/unnamed_6.jpg",
    description: "Short-sleeve wide-leg jumpsuit with iconic 3-Stripe detailing. Effortless one-piece styling.",
    created_at: new Date("2025-02-08")
  },
  {
    id: "11",
    name: "Adidas Originals High-Neck Cropped Tracksuit",
    category: "Women",
    subcategory: "Womens Sport",
    price: 140.00,
    stock: 10,
    badge: "Bestseller",
    image_url: "https://applause.co.zw/uploads/unnamed_7.jpg",
    description: "High-neck cropped tracksuit set with jacket and wide-leg pants. Modern athletic elegance.",
    created_at: new Date("2025-01-25")
  },
  {
    id: "13",
    name: "Adidas Originals Leopard Print Resort Set",
    category: "Women",
    subcategory: "Clothing",
    price: 95.00,
    stock: 14,
    badge: "Bestseller",
    image_url: "https://applause.co.zw/uploads/unnamed_9.jpg",
    description: "Leopard print resort collar button-up shirt and shorts set. Vacation-ready style.",
    created_at: new Date("2025-01-30")
  },
  {
    id: "14",
    name: "Adidas Originals High-Neck Cropped Tracksuit Set",
    category: "Women",
    subcategory: "Womens Sport",
    price: 140.00,
    stock: 10,
    badge: "Bestseller",
    image_url: "https://applause.co.zw/uploads/unnamed_10.jpg",
    description: "High-neck cropped jacket paired with wide-leg pants. Premium athletic set.",
    created_at: new Date("2025-01-28")
  },
  {
    id: "15",
    name: "Adidas Originals Forest Green Track Set",
    category: "Women",
    subcategory: "Clothing",
    price: 130.00,
    stock: 10,
    badge: "New In",
    image_url: "https://applause.co.zw/uploads/unnamed_12.jpg",
    description: "Forest green track jacket and midi skirt set. Sporty sophistication in rich colour.",
    created_at: new Date("2025-02-12")
  },
  {
    id: "16",
    name: "Vintage Marlboro Racing Leather Moto Jacket",
    category: "Men",
    subcategory: "Clothing",
    price: 215.00,
    stock: 4,
    badge: "Bestseller",
    image_url: "https://applause.co.zw/uploads/unnamed_13.jpg",
    description: "Vintage Marlboro racing leather moto jacket. A rare collector's piece for motorsport enthusiasts.",
    created_at: new Date("2025-01-05")
  },
  {
    id: "17",
    name: "Adidas Originals Mesh Knit & Pleated Midi Set",
    category: "Women",
    subcategory: "Clothing",
    price: 115.00,
    stock: 10,
    badge: "New In",
    image_url: "https://applause.co.zw/uploads/unnamed_14.jpg",
    description: "Mesh knit top and pleated midi skirt set. Contemporary elegance meets sporty design.",
    created_at: new Date("2025-02-14")
  },
  {
    id: "18",
    name: "Adidas Originals Resort Shirt & Shorts Set",
    category: "Women",
    subcategory: "Clothing",
    price: 95.00,
    stock: 12,
    badge: "New In",
    image_url: "https://applause.co.zw/uploads/unnamed_15.jpg",
    description: "Resort collar button-up shirt and shorts set. Relaxed warm-weather coordinates.",
    created_at: new Date("2025-02-02")
  },
  {
    id: "19",
    name: "Louis Vuitton Monogram Inspired Denim Set",
    category: "Women",
    subcategory: "Clothing",
    price: 165.00,
    stock: 6,
    badge: "Bestseller",
    image_url: "https://applause.co.zw/uploads/unnamed_16.jpg",
    description: "Monogram-inspired 2-piece denim set with bomber jacket and tiered ruffle skirt. Luxury streetwear.",
    created_at: new Date("2025-01-22")
  },
  {
    id: "20",
    name: "Sleeveless Pleated A-Line Maxi Dress",
    category: "Women",
    subcategory: "New In",
    price: 85.00,
    stock: 15,
    badge: "New In",
    image_url: "https://applause.co.zw/uploads/unnamed_17.jpg",
    description: "Sleeveless pleated A-line maxi dress. Elegant silhouette for any occasion.",
    created_at: new Date("2025-02-06")
  },
  {
    id: "21",
    name: "Adidas Originals Spezial Red Suede Sneakers",
    category: "Men",
    subcategory: "Shoes",
    price: 110.00,
    stock: 8,
    badge: "Bestseller",
    image_url: "https://applause.co.zw/uploads/unnamed_18.jpg",
    description: "Red suede sneakers with gum sole. Iconic Adidas Originals heritage style.",
    created_at: new Date("2025-01-18")
  },
  {
    id: "22",
    name: "Vintage Red Bull Racing Leather Moto Jacket",
    category: "Women",
    subcategory: "Clothing",
    price: 225.00,
    stock: 4,
    badge: "Bestseller",
    image_url: "https://applause.co.zw/uploads/unnamed_20.jpg",
    description: "Vintage Red Bull Racing leather moto jacket. Statement piece for racing fans.",
    created_at: new Date("2025-01-12")
  },
  {
    id: "23",
    name: "Vintage Western Studded Leather Jacket",
    category: "Men",
    subcategory: "Clothing",
    price: 195.00,
    stock: 5,
    badge: null,
    image_url: "https://applause.co.zw/uploads/unnamed_21.jpg",
    description: "Western studded leather jacket with back graphic. Rock and roll attitude.",
    created_at: new Date("2025-01-08")
  },
  {
    id: "24",
    name: "Vintage Monster Energy Racing Leather Jacket",
    category: "Men",
    subcategory: "Mens Sport",
    price: 220.00,
    stock: 4,
    badge: "Bestseller",
    image_url: "https://applause.co.zw/uploads/unnamed_22.jpg",
    description: "Monster Energy racing leather moto jacket. Bold motorsport style.",
    created_at: new Date("2025-01-14")
  },
  {
    id: "25",
    name: "Vintage Sinister Gang Crest Cropped Biker Jacket",
    category: "Men",
    subcategory: "Discover",
    price: 240.00,
    stock: 3,
    badge: "New In",
    image_url: "https://applause.co.zw/uploads/unnamed_23.jpg",
    description: "Cropped leather biker jacket with crest graphic. Edgy vintage style.",
    created_at: new Date("2025-02-15")
  },
  {
    id: "26",
    name: "Vintage McLaren Racing Leather Bomber Jacket",
    category: "Men",
    subcategory: "Clothing",
    price: 230.00,
    stock: 4,
    badge: null,
    image_url: "https://applause.co.zw/uploads/unnamed_24.jpg",
    description: "McLaren Racing leather Grand Prix bomber jacket. Premium motorsport heritage.",
    created_at: new Date("2025-01-20")
  },
  {
    id: "27",
    name: "Vintage Dainese Yama Moto 72 Racing Jacket",
    category: "Men",
    subcategory: "Clothing",
    price: 235.00,
    stock: 3,
    badge: null,
    image_url: "https://applause.co.zw/uploads/unnamed_25.jpg",
    description: "Dainese Yama Moto 72 leather racing jacket. Italian craftsmanship meets racing legacy.",
    created_at: new Date("2025-01-26")
  },
  {
    id: "28",
    name: "Vintage Avirex Two-Tone Leather Varsity Jacket",
    category: "Men",
    subcategory: "Clothing",
    price: 260.00,
    stock: 3,
    badge: null,
    image_url: "https://applause.co.zw/uploads/unnamed_26.jpg",
    description: "Avirex New York two-tone leather varsity jacket. American heritage luxury.",
    created_at: new Date("2025-01-03")
  },
  {
    id: "29",
    name: "Vintage Yamaha Racing Leather Moto Jacket",
    category: "Men",
    subcategory: "Clothing",
    price: 225.00,
    stock: 4,
    badge: "Bestseller",
    image_url: "https://applause.co.zw/uploads/unnamed_28.jpg",
    description: "Yamaha Racing leather moto jacket. Iconic racing branding on premium leather.",
    created_at: new Date("2025-01-07")
  },
  {
    id: "30",
    name: "Vintage EPIUM Studded Leather Bomber Jacket",
    category: "Men",
    subcategory: "Mens Sport",
    price: 250.00,
    stock: 3,
    badge: "New In",
    image_url: "https://applause.co.zw/uploads/unnamed_29.jpg",
    description: "EPIUM studded 00 leather bomber jacket. Statement piece with rock-inspired detailing.",
    created_at: new Date("2025-02-02")
  },
  {
    id: "31",
    name: "Vintage Scarface Half-and-Half Leather Bomber",
    category: "Men",
    subcategory: "Mens Sport",
    price: 250.00,
    stock: 3,
    badge: "Bestseller",
    image_url: "https://applause.co.zw/uploads/unnamed_30.jpg",
    description: "Scarface half-and-half leather bomber jacket. Cinematic style meets luxury outerwear.",
    created_at: new Date("2025-01-16")
  },
  {
    id: "32",
    name: "Vintage Japanese Kanji Graphic Leather Jacket",
    category: "Men",
    subcategory: "Clothing",
    price: 220.00,
    stock: 4,
    badge: null,
    image_url: "https://applause.co.zw/uploads/unnamed_31.jpg",
    description: "Japanese Kanji graphic leather moto jacket. Cultural fusion meets vintage leather.",
    created_at: new Date("2025-01-22")
  },
  {
    id: "33",
    name: "Vintage NY Monogram Studded Leather Bomber",
    category: "Men",
    subcategory: "Clothing",
    price: 245.00,
    stock: 3,
    badge: "Bestseller",
    image_url: "https://applause.co.zw/uploads/unnamed_33.jpg",
    description: "NY monogram studded leather bomber jacket. Urban luxury with rock-inspired studs.",
    created_at: new Date("2025-01-09")
  },
  {
    id: "34",
    name: "Vintage Ferrari Racing Leather Moto Jacket",
    category: "Men",
    subcategory: "Mens Sport",
    price: 230.00,
    stock: 4,
    badge: "New In",
    image_url: "https://applause.co.zw/uploads/unnamed_34.jpg",
    description: "Ferrari racing leather moto jacket. Legendary Italian motorsport heritage.",
    created_at: new Date("2025-02-10")
  },
  {
    id: "a1",
    name: "New York Yankees Two-Tone Baseball Hat",
    category: "Accessories",
    subcategory: "Hats",
    price: 34.99,
    stock: 20,
    badge: null,
    image_url: "/uploads/hat-3.jpg",
    description: "Classic two-tone New York Yankees baseball cap with embroidered logo. A timeless streetwear staple.",
    created_at: new Date("2025-03-01")
  },
  {
    id: "a2",
    name: "Classic Caps Collection",
    category: "Accessories",
    subcategory: "Hats",
    price: 24.99,
    stock: 25,
    badge: null,
    image_url: "/uploads/hat-1.jpg",
    description: "Versatile everyday cap with a clean, minimal design. Fits your daily rotation.",
    created_at: new Date("2025-03-02")
  },
  {
    id: "a3",
    name: "Classic Caps Collection 2",
    category: "Accessories",
    subcategory: "Hats",
    price: 24.99,
    stock: 22,
    badge: null,
    image_url: "/uploads/hat-2.jpg",
    description: "Everyday cap with a clean silhouette and secure fit. A wardrobe essential.",
    created_at: new Date("2025-03-03")
  },
  {
    id: "a4",
    name: "Everyday Carry Bag",
    category: "Accessories",
    subcategory: "Bags",
    price: 49.99,
    stock: 15,
    badge: "Bestseller",
    image_url: "/uploads/bag-1.jpg",
    description: "Stylish everyday carry bag with durable construction and smart storage.",
    created_at: new Date("2025-03-04")
  },
  {
    id: "a5",
    name: "Everyday Carry Bag 2",
    category: "Accessories",
    subcategory: "Bags",
    price: 49.99,
    stock: 14,
    badge: null,
    image_url: "/uploads/bag-2.jpg",
    description: "Versatile carry bag combining form and function for every day.",
    created_at: new Date("2025-03-05")
  },
  {
    id: "a6",
    name: "Stand Oil Chubby Bag",
    category: "Accessories",
    subcategory: "Bags",
    price: 54.99,
    stock: 10,
    badge: "New In",
    image_url: "/uploads/bag-3.jpg",
    description: "Trendy chubby silhouette bag with a soft, stylish finish. A bold statement piece.",
    created_at: new Date("2025-03-06")
  },
  {
    id: "a7",
    name: "Classic Leather Belt",
    category: "Accessories",
    subcategory: "Belts",
    price: 29.99,
    stock: 30,
    badge: null,
    image_url: "/uploads/belt-1.jpg",
    description: "Timeless leather belt with a polished buckle. Complements any outfit.",
    created_at: new Date("2025-03-07")
  },
  {
    id: "a8",
    name: "Classic Leather Belt 2",
    category: "Accessories",
    subcategory: "Belts",
    price: 29.99,
    stock: 28,
    badge: null,
    image_url: "/uploads/belt-2.jpg",
    description: "Durable leather belt with clean detailing for everyday wear.",
    created_at: new Date("2025-03-08")
  },
  {
    id: "a9",
    name: "Diesel Logo-Buckle Leather Belt",
    category: "Accessories",
    subcategory: "Belts",
    price: 39.99,
    stock: 18,
    badge: "Bestseller",
    image_url: "/uploads/belt-3.jpg",
    description: "Premium leather belt featuring a signature Diesel logo buckle. Designer edge for any look.",
    created_at: new Date("2025-03-09")
  },
  {
    id: "a10",
    name: "Statement Sunglasses",
    category: "Accessories",
    subcategory: "Sunglasses",
    price: 26.99,
    stock: 35,
    badge: null,
    image_url: "/uploads/sunglass-1.jpg",
    description: "Sleek sunglasses with UV protection and a bold frame. Elevate any look.",
    created_at: new Date("2025-03-10")
  },
  {
    id: "a11",
    name: "Chrome Hearts Sunglasses",
    category: "Accessories",
    subcategory: "Sunglasses",
    price: 45.99,
    stock: 12,
    badge: "Bestseller",
    image_url: "/uploads/sunglass-2.jpg",
    description: "Chrome Hearts-inspired frames with premium detailing. A luxury eyewear statement.",
    created_at: new Date("2025-03-11")
  },
  {
    id: "a12",
    name: "Statement Sunglasses 2",
    category: "Accessories",
    subcategory: "Sunglasses",
    price: 26.99,
    stock: 32,
    badge: null,
    image_url: "/uploads/sunglass-3.jpg",
    description: "Modern sunglasses with a clean frame and full UV protection.",
    created_at: new Date("2025-03-12")
  },
  {
    id: "a13",
    name: "Statement Sunglasses 3",
    category: "Accessories",
    subcategory: "Sunglasses",
    price: 26.99,
    stock: 30,
    badge: null,
    image_url: "/uploads/sunglass-4.jpg",
    description: "Bold sunglasses with comfortable fit and sharp styling.",
    created_at: new Date("2025-03-13")
  },
  {
    id: "a14",
    name: "Classic Compact Wallet",
    category: "Accessories",
    subcategory: "Wallets",
    price: 19.99,
    stock: 40,
    badge: null,
    image_url: "/uploads/wallet-1.jpg",
    description: "Slim, functional wallet with plenty of card slots. Everyday convenience.",
    created_at: new Date("2025-03-14")
  },
  {
    id: "a15",
    name: "Classic Compact Wallet 2",
    category: "Accessories",
    subcategory: "Wallets",
    price: 19.99,
    stock: 38,
    badge: null,
    image_url: "/uploads/wallet-2.jpg",
    description: "Compact leather wallet engineered for everyday carrying essentials.",
    created_at: new Date("2025-03-15")
  },
  {
    id: "a16",
    name: "High-Quality Men's Wallet",
    category: "Accessories",
    subcategory: "Wallets",
    price: 27.99,
    stock: 26,
    badge: "Bestseller",
    image_url: "/uploads/wallet-3.jpg",
    description: "Premium men's wallet with custom cross pattern and multiple compartments. Compact and convenient.",
    created_at: new Date("2025-03-16")
  },
  {
    id: "a17",
    name: "Burgundy Leather Gift Set",
    category: "Accessories",
    subcategory: "Wallets",
    price: 34.99,
    stock: 12,
    badge: "New In",
    image_url: "/uploads/wallet-4.jpg",
    description: "Burgundy leather gift set for women - wallet, keychain and card holder by SOLIDO. The perfect gift.",
    created_at: new Date("2025-03-17")
  },
  {
    id: "a18",
    name: "Cute Card Holder for Girls",
    category: "Accessories",
    subcategory: "Wallets",
    price: 14.99,
    stock: 45,
    badge: null,
    image_url: "/uploads/wallet-5.jpg",
    description: "Aesthetic, cute card holder designed for girls. Compact and adorable.",
    created_at: new Date("2025-03-18")
  },
  {
    id: "a19",
    name: "Men's Bags & Wallets Collection",
    category: "Accessories",
    subcategory: "Wallets",
    price: 32.99,
    stock: 15,
    badge: null,
    image_url: "/uploads/bags-wallets.jpg",
    description: "Curated men's bags and wallets collection. Function meets refined style.",
    created_at: new Date("2025-03-19")
  },
  {
    id: "n1",
    name: "PrettyGarden Women's Summer 2-Piece Set",
    category: "New In",
    subcategory: "Discover",
    price: 89.99,
    stock: 12,
    badge: "New In",
    image_url: "/uploads/newin-1.jpg",
    description: "Fresh two-piece summer set from PrettyGarden. Effortless warm-weather style.",
    created_at: new Date("2025-04-01")
  },
  {
    id: "n2",
    name: "Business Outfits Collection",
    category: "New In",
    subcategory: "Discover",
    price: 75.00,
    stock: 15,
    badge: "New In",
    image_url: "/uploads/newin-2.jpg",
    description: "Polished business outfits for a sharp, professional look.",
    created_at: new Date("2025-04-02")
  },
  {
    id: "n3",
    name: "Dalila Maxi Dress",
    category: "New In",
    subcategory: "Discover",
    price: 95.00,
    stock: 10,
    badge: "New In",
    image_url: "/uploads/newin-3.jpg",
    description: "Elegant Dalila maxi dress with a flowing silhouette. Beautiful for any occasion.",
    created_at: new Date("2025-04-03")
  },
  {
    id: "n4",
    name: "Fresh Green Summer Outfit",
    category: "New In",
    subcategory: "Discover",
    price: 65.00,
    stock: 18,
    badge: "New In",
    image_url: "/uploads/newin-4.jpg",
    description: "Casual clean-girl aesthetic in a fresh green summer outfit. Everyday effortless.",
    created_at: new Date("2025-04-04")
  },
  {
    id: "n5",
    name: "Modern Aesthetic Outfit for Men",
    category: "New In",
    subcategory: "Discover",
    price: 70.00,
    stock: 16,
    badge: "New In",
    image_url: "/uploads/newin-5.jpg",
    description: "Modern and aesthetic menswear outfit with clean, contemporary styling.",
    created_at: new Date("2025-04-05")
  },
  {
    id: "n6",
    name: "Modern Men's Outfit by ANTONIOSCLOTHING",
    category: "New In",
    subcategory: "Discover",
    price: 85.00,
    stock: 10,
    badge: "New In",
    image_url: "/uploads/newin-6.jpg",
    description: "Premium men's outfit inspired by ANTONIOSCLOTHING. Statement modern menswear.",
    created_at: new Date("2025-04-06")
  },
  {
    id: "n7",
    name: "Red Athletic Sweatshirt & Jogger Set",
    category: "New In",
    subcategory: "Discover",
    price: 78.00,
    stock: 20,
    badge: "New In",
    image_url: "/uploads/newin-7.jpg",
    description: "Red athletic sweatshirt and jogger set. Sporty comfort for everyday wear.",
    created_at: new Date("2025-04-07")
  },
  {
    id: "n8",
    name: "Men's Summer Outfit with Drawstring",
    category: "New In",
    subcategory: "Discover",
    price: 68.00,
    stock: 14,
    badge: "New In",
    image_url: "/uploads/newin-8.jpg",
    description: "Breezy men's summer outfit with drawstring detail. Relaxed warm-weather styling.",
    created_at: new Date("2025-04-08")
  }
];

const adminCredentials = {
  username: "admin",
  password: "found2025"
};

const customers = [
  { id: "1", name: "Tatenda Moyo", phone: "+263771234567", email: "tatenda@email.com", orders: 3, total_spent: 185.00, since: "2025-01-10" },
  { id: "2", name: "Nkosazana Dlamini", phone: "+263772345678", email: "nkosa@email.com", orders: 1, total_spent: 78.00, since: "2025-01-20" },
  { id: "3", name: "Blessing Chikowero", phone: "+263773456789", email: "blessing@email.com", orders: 5, total_spent: 312.00, since: "2025-01-05" },
  { id: "4", name: "Rudo Mapfumo", phone: "+263774567890", email: "", orders: 2, total_spent: 96.00, since: "2025-02-01" },
  { id: "5", name: "Tawanda Sithole", phone: "+263775678901", email: "tawanda@email.com", orders: 1, total_spent: 89.00, since: "2025-02-05" }
];

module.exports = { products, adminCredentials, customers };
